### ISSUE TITLE
Allow `import` statements

### ISSUE THREAD

**Issue by adrelino** [qooxdoo/qooxdoo#10393]
To allow `import` statements, 

1. the babel parser option `sourceType` (https://babeljs.io/docs/en/options#sourcetype) needs to be configurable, which is not possible currently as it is hard-coded to `script` currently in the qx compiler source:

https://github.com/qooxdoo/qooxdoo/blob/b470c93b00a99f830fed4f0dc566c2bce9c05e42/source/class/qx/tool/compiler/ClassFile.js#L401

Setting it to `unambiguous` or `module` allows files with import statements to be parsed.

2. However, when loading the resulting files in a browser, even if index.js is included with "module" source type results in an error, because the import statements do not end up at the top of the files after qx compiles them but somewhere in the middle (after `dbClassInfo`. Anyone knows how to fix that?

**Comment by johnspackman** [comment]
are you saying that the `import` statements remain in the code that is generated?  AIUI browsers do not support import

**Comment by adrelino** [comment]
yes, they should stay in the code. All modern browsers support `import` [e.g. since Chrome 61](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility). Because our qooxdoo application (and es6 module-based library) is huge, at least during development, I only want to bundle what is absolutely necessary. This is the motivation followed by [vitejs.dev](https://vitejs.dev/guide/why.html#the-problems):

> Before ES modules were available in browsers, developers had no native mechanism for authoring JavaScript in a modularized fashion. This is why we are all familiar with the concept of "bundling": using tools that crawl, process and concatenate our source modules into files that can run in the browser.

> Over time we have seen tools like [webpack](https://webpack.js.org/), [Rollup](https://rollupjs.org/) and [Parcel](https://parceljs.org/), which greatly improved the development experience for frontend developers.

> However, as we start to build more and more ambitious applications, the amount of JavaScript we are dealing with also increased exponentially. It is not uncommon for large scale projects to contain thousands of modules. We are starting to hit a performance bottleneck for JavaScript based tooling: it can often take an unreasonably long wait (sometimes up to minutes!) to spin up a dev server, and even with HMR, file edits can take a couple seconds to be reflected in the browser. The slow feedback loop can greatly affect developers' productivity and happiness.

> Vite aims to address these issues by leveraging new advancements in the ecosystem: the availability of native ES modules in the browser, and the rise of JavaScript tools written in compile-to-native languages.


At the moment, I am actually not even using vite, but [modern-web dev server](https://modern-web.dev/guides/going-buildless/es-modules/)  during developmen and [rollup](https://rollupjs.org/) for bundling only during deployment.

**Comment by adrelino** [comment]
The same problem is mentioned here https://github.com/qooxdoo/qooxdoo/issues/10398#issuecomment-1129264043 :
> imports have to be at the top of the file, but when we transpile the code we add wrappers a

**Comment by johnspackman** [comment]
This should be fixed with https://github.com/qooxdoo/qooxdoo/pull/10400

**Comment by adrelino** [comment]
> This should be fixed with #10400

So I should use `require` instead of `import` everywhere?

**Comment by johnspackman** [comment]
no, you can use `import` (or `require`) but behind the scenes, the compiler will delete the `import` (or `require`) and automatically bundle whatever you wanted to import into code.  Your browser will not have to load any modules because the compiler will have done it for you/it

**Comment by hkollmann** [comment]
@adrelino : Can this be closed?

**Comment by adrelino** [comment]
> @adrelino : Can this be closed?

I just tested again with a fresh installation of qooxdoo, but it is still not working.

Using `import { foo } from ".bar.js"` at the top of qooxdoo class files, e.g. `Application.js`, does not work, even if in `boot/index.html` I replace `<script type="text/javascript" src="${appPath}index.js"></script>`  with `<script type="module" src="${appPath}index.js"></script>`:

```
$ qx compile
Making applications...
TypeError: Cannot assign to read only property 'message' of object 'SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
myapp.Application: error: FATAL Syntax error: Cannot assign to read only property 'message' of object 'SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:0)
Consider renaming the file to '.mjs', or setting sourceType:module or sourceType:unambiguous in your Babel config for this file.'
qx.util.Uuid:94: automatically detected 'require(crypto)`
Cannot write application 'myapp' because it has fatal errors
```

I appreciate your efforts with localModules and require and browserify, but at least for me, this is the wrong direction: the qx compiler should actually do *less* instead of more and just leave the `import` statements as they are in the code.
