### ISSUE TITLE
menubar buttons do not react on click on chrome 55 (solved with PR #9219 in master)

### ISSUE THREAD

**Issue by level420** [qooxdoo/qooxdoo#9182]
Verified on windows 7x64 with chrome 54.0.2840.27 beta-m (64-bit)

To reproduce open http://www.qooxdoo.org/devel/demobrowser/#widget~MenuBar.html or http://www.qooxdoo.org/current/demobrowser/#widget~MenuBar.html and click on e.g. the "File" menu entry.

The file "File" menu button gets hovered, but does not open the menu pane with the sub menues.

**Comment by level420** [comment]
I may have come in because of a deprecation warning which now shows up in the console:
```
Event.js:52 Navigator.pointerEnabled is a non-standard API added for experiments only. It will be removed in near future.qx.bom.client.Event.getMsPointer() @ Event.js:52qx.core.Environment.get() @ Environment.js:906defer @ Environment.js:83(anonymous function) @ Bootstrap.js:205qx.Bootstrap.addPendingDefer() @ Bootstrap.js:431qx.Bootstrap.define() @ Bootstrap.js:204(anonymous function) @ Environment.js:39
Native.js:58 003612 qx.core.Init: Load runtime: 3611ms
```

**Comment by level420** [comment]
Works as expected without showing the bug on windows 7x64 with chrome Version 53.0.2785.116 m (64-bit)

**Comment by cajus** [comment]
Not reproducible on linux with latest Chrome 54 beta.

**Comment by level420** [comment]
Reproducible on windows 10 with chrome 54 beta.

**Comment by level420** [comment]
It seems that in ```qx.ui.form.MenuButton``` at https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/form/MenuButton.js#L190 the ```_onPointerDown``` event handler is processed twice, which means first opening and then closing the menu.

**Comment by level420** [comment]
quick workarround: open and close the menu of the menu button asynchronously:
```diff
--- a/framework/source/class/qx/ui/form/MenuButton.js
+++ b/framework/source/class/qx/ui/form/MenuButton.js
@@ -200,9 +200,9 @@ qx.Class.define("qx.ui.form.MenuButton",
       if (menu) {
         // Toggle sub menu visibility
         if (!menu.isVisible()) {
-          this.open();
+          qx.event.Timer.once(this.open, this, 0);
         } else {
-          menu.exclude();
+          qx.event.Timer.once(this.exclude, menu, 0);
         }
 
         // Event is processed, stop it for others
```

**Comment by level420** [comment]
let's see if this persists in the next beta.

**Comment by level420** [comment]
the issue is still there on chrome 54.0.2840.34 beta-m (64-bit) on windows 7 x64

**Comment by level420** [comment]
not reproducible on OS X 10.11.6 with chrome Version 54.0.2840.34 beta (64-bit)

**Comment by level420** [comment]
the issue is still there on chrome Version 54.0.2840.50 beta-m (64-bit) on windows 7 x64

**Comment by slachtar** [comment]
the workaround works great. thanks.

**Comment by level420** [comment]
@slachtar could you please tell me which browser version you are using on which OS exactly?

I'm asking because I cant't reproduce the issue anymore on windows 7x64 with chrome version Version ```54.0.2840.59 m (64-bit)``` which is the stable release, but can still reproduce it with Version ```54.0.2840.59 beta-m (64-bit)```.

**Comment by level420** [comment]
The issue is again there with chrome ```55.0.2883.21 beta-m (64-bit)``` on windwos 7x64.

**Comment by level420** [comment]
This may be related to the new "auxclick" event. See
https://developers.google.com/web/updates/2016/10/auxclick
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/R8OehqGJzt0
https://www.chromestatus.com/features/5663174342737920

**Comment by level420** [comment]
I think I found the change in chrome which causes this issue:
https://developers.google.com/web/updates/2016/10/pointer-events

It may be that at some point they already shipped the change with chrome 54 beta and decided to retract it for 54 stable.

We can detect the new behaviour in chrome by checking ```window.PointerEvent``` as documented here:
https://developers.google.com/web/updates/2016/10/pointer-events#browser_support.

The solution would be to add this check to ```qx.bom.client.Event.getMsPointer``` to return ```true``` which leads to ```qx.core.Environment.get("event.mspointer")``` for chrome 55 on.

I'll create a PR for this.

**Comment by level420** [comment]
As opera also uses blink, this will hit opera on version 42. See http://caniuse.com/#feat=pointer

**Comment by level420** [comment]
Fixed via https://github.com/qooxdoo/qooxdoo/pull/9219

**Comment by level420** [comment]
One additional note:

Chrome 55 was released today and it seems that they decided to to retract the pointer event feature in the stable version 55.0.2883.75, while it is still there in the also today released 55.0.2883.75 beta from the beta channel.

This shows that in most cases it is better to use feature detection and not rely on browser version detection.

But we are prepared now, at least for the upcoming pointer events in chrome.

**Comment by vvandens** [comment]
Wow! you saved my day. Thanks!

**Comment by level420** [comment]
@vvandens you're welcome!

**Comment by vvandens** [comment]
@level420 a side question : I try to cleanly patch an application that must stay on 5.0.1 release until next release is available. I simply copy-pasted the latest static method getMsPointer you fixed in one of the application class, then when the application starts, I call :
```
qx.core.Environment.invalidateCacheKey("event.mspointer");
qx.core.Environment.add("event.mspointer", my.own.Class.getMsPointer);
```
However, the bug is still there in the application.
Tested the devel demo browser and everything is fine there, so I suspect I must be missing something... Any hint ?

**Comment by alp82** [comment]
Thx vvandens for your workaround solution. I tried to use this method but menues are still not working. While debugging i saw that `qx.core.Environment.add` did nothing because the `_checks` array already contained the `event.mspointer` value.

I replaced the defer method with:
    defer: function (statics) {
        qx.core.Environment.invalidateCacheKey("event.mspointer");
        delete qx.core.Environment.getChecks()['event.mspointer'];
        qx.core.Environment.add("event.mspointer", statics.getPatchedMsPointer);
    }

But still no dice, menues don't work. Any idea?

**Comment by level420** [comment]
@alp82 it seems that @vvandens solution managed to add the key function _before_ the original code is setting the key.

@vvandens could you help here? thank you!

**Comment by eflowbeach** [comment]
Not a permanent fix, but this override seemed to temporarily patch my 5.0.1 app:
```
qx.Class.define("edd.JQx.MenuButton",
{
  extend : qx.ui.form.MenuButton,
  construct : function(label, icon, menu)
  {
    var me = this;
    this.base(arguments, label, icon);

    // Initialize properties
    if (menu != null) {
      this.setMenu(menu);
    }
    me.addListener("pointerdown", function(e) {
      me.open();
    }, this);
  }
});
```

This probably creates more problems than it fixes though.

**Comment by level420** [comment]
@eflowbeach you could add the following lines https://github.com/qooxdoo/qooxdoo/pull/9219/files to your local copy of qooxdoo.

**Comment by eflowbeach** [comment]
@level420 After I posted my comment, I realized that it was only a few lines of code. Thanks for the suggestion, it works like a charm now!

**Comment by vogelor** [comment]
i am using Version 55.0.2883.87 m at windows 10 64 bit and the menu-button stopped working. After patching #9219 by hand, it works again! so thank you for your great job!

**Comment by level420** [comment]
Also fixed in release https://github.com/qooxdoo/qooxdoo/releases/tag/release_5_0_2
